from __future__ import annotations

import csv
import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


def write_release_artifacts(
    output_dir: Path,
    examples: list[dict[str, Any]],
    split_manifest: dict[str, Any],
    clean_report: dict[str, Any],
) -> None:
    stats = build_stats(examples, clean_report)
    (output_dir / "stats.json").write_text(json.dumps(stats, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (output_dir / "hashes.json").write_text(
        json.dumps(split_manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (output_dir / "prep_log.txt").write_text(_prep_log(clean_report), encoding="utf-8")
    (output_dir / "README.md").write_text(_readme(stats), encoding="utf-8")
    (output_dir / "MANIFEST.md").write_text(_manifest_md(examples, stats), encoding="utf-8")
    _write_license_matrix(output_dir / "LICENSE-MATRIX.csv", examples)


def build_stats(examples: list[dict[str, Any]], clean_report: dict[str, Any]) -> dict[str, Any]:
    by_source = Counter(str(example.get("source_id", "unknown")) for example in examples)
    by_category = Counter(str(example.get("category", "unknown")) for example in examples)
    by_sport = Counter(str(example.get("sport", "unknown")) for example in examples)
    return {
        "total_examples": len(examples),
        "by_source": dict(sorted(by_source.items())),
        "by_category": dict(sorted(by_category.items())),
        "by_sport": dict(sorted(by_sport.items())),
        "clean_report": clean_report,
    }


def _write_license_matrix(path: Path, examples: list[dict[str, Any]]) -> None:
    sources: dict[str, dict[str, Any]] = defaultdict(dict)
    for example in examples:
        source_id = str(example.get("source_id", "unknown"))
        sources[source_id] = {
            "source_id": source_id,
            "license_kind": example.get("license_kind", ""),
            "license_verified": str(bool(example.get("license_verified"))).lower(),
            "requires_human_approval": str(bool(example.get("requires_human_approval"))).lower(),
            "example_count": int(sources[source_id].get("example_count", 0)) + 1,
        }

    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=["source_id", "license_kind", "license_verified", "requires_human_approval", "example_count"],
        )
        writer.writeheader()
        for row in sorted(sources.values(), key=lambda item: item["source_id"]):
            writer.writerow(row)


def _manifest_md(examples: list[dict[str, Any]], stats: dict[str, Any]) -> str:
    lines = [
        "# ЛИИ-Спорт SFT Corpus v0.1",
        "",
        f"- Examples: {len(examples)}",
        "- 152-ФЗ posture: public/open sports-domain materials only; PII scrub gate applied.",
        "- Bench leakage: exact/fuzzy question check applied against `data/questions.json`.",
        "- Release state: validation batch unless explicitly scaled after review.",
        "",
        "## Sources",
        "",
        "| Source | Examples |",
        "|---|---:|",
    ]
    for source_id, count in stats["by_source"].items():
        lines.append(f"| {source_id} | {count} |")
    lines.append("")
    return "\n".join(lines)


def _readme(stats: dict[str, Any]) -> str:
    return (
        "# Corpus Snapshot\n\n"
        "Generated by `tools/corpus-prep`.\n\n"
        f"Examples: {stats['total_examples']}\n\n"
        "Files: train/val/test JSONL, MANIFEST, LICENSE-MATRIX, hashes, stats, prep log.\n"
    )


def _prep_log(clean_report: dict[str, Any]) -> str:
    return json.dumps(clean_report, ensure_ascii=False, indent=2) + "\n"
